[project]
name = "Blind-Walk"
version = "0.1"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icecream>=2.1.4",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5"
]
